// === APPLICATION'S LAYOUT RESOURCE ===
export const SET_IS_LOADING_LAYOUT = "SET_IS_LOADING_LAYOUT";
export const SET_DATA_ALERT_CONFIRM = "SET_DATA_ALERT_CONFIRM";

// === APPLICATION RESOURCES ===
export const SET_DATA_USER = "SET_DATA_USER";
export const SET_DATA_LAYOUT = "SET_DATA_LAYOUT";
